# Generated by Django 5.2.3 on 2025-08-07 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('pampers', 'Pampers'), ('soap', 'Soap'), ('stroller', 'Stroller'), ('bottle', 'Bottle'), ('boys', "Boy's Fashions"), ('girls', "Girl's Fashions"), ('offers', 'Offers')], max_length=20)),
                ('image', models.ImageField(upload_to='products/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mrp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('rating', models.PositiveIntegerField(default=0)),
                ('is_new', models.BooleanField(default=True)),
            ],
        ),
    ]
