# Generated by Django 5.2.3 on 2025-08-09 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_cartitem_session_key_alter_cartitem_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('pampers', 'Pampers'), ('soap', 'Soap'), ('stroller', 'Stroller'), ('bottle', 'Bottle'), ('boys', "Boy's Fashions"), ('girls', "Girl's Fashions"), ('offers', 'Offers')], max_length=100),
        ),
    ]
